#docker-compose -p dispenser-api up -d
version: "3.7"

volumes:
  dispenser_data:

services:
  backend:
    image: dispenser-api
#    depends_on:
#      - database
    ports: 
      - "8080:8080"
    build:
      context: .
      dockerfile: deploy/back-dockerfile
    volumes:
      - dispenser_data:/dispenser_api

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  frontend:
    image: nginx
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: deploy/front-dockerfile